apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    editable: true
    jsonData:
      defaultDatabase: otel
      port: 9000
      host: clickhouse
      username: otel
      tlsSkipVerify: false
      protocol: native
      logs:
        defaultDatabase: otel
        defaultTable: otel_logs
        otelEnabled: true
      traces:
        defaultDatabase: otel
        defaultTable: otel_traces
        otelEnabled: true
        durationUnit: nanoseconds
    secureJsonData:
      password: otel
